---
kind : service
name : S
kubename : "127.0.0.1:8000"
inputs : 
 - { name : a }
 
outputs:
 - { name : res }
# - { name : tab1, array: true, size: 3}
#- tab0, tab1, tab2, ...,tab4
 
---
kind : service
name : S1
kubename : "127.0.0.1:8000"
inputs :
- { name : a }
 
outputs:
 - { name : res }
 - { name : tab, array: true, size: 3}
 
---
kind : service
name : S2
kubename : "127.0.0.1:8000"
inputs : 
 - { name : a }
 - { name : tab1, array: true, size: 3}
 
outputs:
 - { name : b }
 
---
kind : service
name : S3
kubename : "127.0.0.1:8000"
inputs : 
 - { name : syncIn }
 - { name : a }
outputs:
 - { name : b }
 - { name : syncOut }