---
kind : service
name : S
kubename : "127.0.0.1:8000"
inputs : 
 - { name : a }
 - { name : b}
 
outputs:
 - { name : c }
 - { name : d }
 - { name : tab, array: true, size: 5}
#- tab0, tab1, tab2, ...,tab4
 
---
kind : service
name : S1
kubename : "127.0.0.1:8000"
inputs : 
 - { name : a }
 - { name : b}
 
outputs:
 - { name : c }
 - { name : tab, array: true, size: 5}
 
---
kind : service
name : S2
kubename : "127.0.0.1:8000"
inputs : 
 - { name : a }
 - { name : tab1, array: true, size: 5}
 
outputs:
 - { name : b }